name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build main.go

    - name: Test
      run: go test -v .
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.2.0
      with:
        # Arguments for the git add command
        add: main
        # The name of the user that will be displayed as the author of the commit
        author_name: Saggin Bot
        # The message for the commit
        message: Gtihub Actions Saggin Bot
        # Name of the branch to use, if different from the one that triggered the workflow
        ref: master

    - uses: actions/checkout@master
    - name: Commit files
      run: |
        git config --local user.email "saggins@github.com"
        git config --local user.name "GitHub Action Discord-bot"
        git add main
        git commit -m "Add bin"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN
        directory: bin
        repository: saggin-php
