name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go build main.go
        
    - name: Build & Commit files
      uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'main'

        # The message for the commit
        # Default: 'Commit from GitHub Actions'
        message: 'sdf'

        # Name of the branch to use, if different from the one that triggered the workflow
        # Default: the branch that triggered the workflow (from GITHUB_REF)
        ref: 'master'

        # The arguments for the `git rm` command (see the paragraph below for more info)
        # Default: ''
        remove: "./main"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        repository: saggins/saggin-php.git

