# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3

    # Runs a single command using the runners shell
    - name: go build main.go
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.2.0
      with:
        # Arguments for the git add command
        add: main
        # The name of the user that will be displayed as the author of the commit
        author_name: Saggin Bot
        # The directory where your repository is located. You should use actions/checkout first to set it up
        cwd: ./bin
        # The message for the commit
        message: Gtihub Actions Saggin Bot
        # Name of the branch to use, if different from the one that triggered the workflow
        ref: master
